server:
  port: 8080

axon:
  axonserver:
    serializer:
      general: xstream
      events: jackson
      messages: jackson
    servers: 192.168.0.249:18124


spring:
  application:
    name: practice
  datasource:
    url: jdbc:mariadb://192.168.0.249:10011/axon_test
    username: kts
    password: qwer1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

#
#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace


